name: BSN Backend API pipeline

on:
  push:
    branches:
      - ci/pipeline
    paths:
      - spring-book/**
      - docker/backend/Docker
      - 'docker-compose.yaml'
      - .github/workflows/*-backend.yaml

jobs:
  compile:
    runs-on: ubuntu-latest
    name: compile project
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-jdk@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Compile Project
        run: |
          cd spring-book
          ./mvnw clean compile


  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-jdk@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Running unit test
        run: |
          cd spring-book
          ./mvnw clean test
  

  build:
    runs-on: ubuntu-latest
    name: Build Backend
    needs: [compile, unit-tests]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-jdk@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build Project
        run: |
          cd spring-book
          ./mvnw clean package

  build-image:
    runs-on: ubuntu-latest
    name: Building docker image
    needs: [build]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-jdk@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build Project
        run: |
          cd spring-book
          ./mvnw clean package

      - name: Extract project version
        id: extract_version
        run: |
          cd spring-book
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to Dockerhub
        uses: docker/docker-push-action@v5
        with:
          context: spring-book
          file: docker/backend/Dockerfile
          push: true

          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bsn-api:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKERHUB_USERNAME }}/bsn-api:latest
          build-args: |
            PROFILE=dev
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}
            
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: Create deployment folder
        run: ssh ${{ secrets.VPS_USERNAME }}@{{ secrets.VPS_IP }} "mkdir -p ci-cd"

      - name: Copy docker compose file
        run: scp docker-compose.yaml ${{ secrets.VPS_USERNAME }}@{{ secrets.VPS_IP }}:ci-cd/docker-compose.yaml

      - name: Set ENV variables and Deploy
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@{{ secrets.VPS_IP }} <<EOF
          export EMAIL_HOST_NAME=${{ secrets.EMAIL_HOST_NAME }}
          export EMAIL_USER_NAME=${{ secrets.EMAIL_USER_NAME }}
          export EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          cd ci-cd
          docker-compose -f docker-compose.yaml pull -q
          docker-compose -f docker-compose.yaml up -d
          EOF